const finance = require('../models').finance;

module.exports = { 
    add(req, res) {
      return finance
        .create({
          case_id: req.body.case_id ? req.body.case_id : null,
          cvrnr: req.body.cvrnr ? req.body.cvrnr : null,
          reportingperiodstartdate: req.body.reportingperiodstartdate ? req.body.reportingperiodstartdate : null,
          reportingperiodenddate: req.body.reportingperiodenddate ? req.body.reportingperiodenddate : null,
          dateofapprovalofannualreport: req.body.dateofapprovalofannualreport ? req.body.dateofapprovalofannualreport : null,
          dateofgeneralmeeting: req.body.dateofgeneralmeeting ? req.body.dateofgeneralmeeting : null,
          informationontypeofsubmittedreport: req.body.informationontypeofsubmittedreport ? req.body.informationontypeofsubmittedreport : null,
          typeofauditorassistance: req.body.typeofauditorassistance ? req.body.typeofauditorassistance : null,
          classofreportingentity: req.body.classofreportingentity ? req.body.classofreportingentity : null,
          indentificationnumbercvrofauditfirm: req.body.indentificationnumbercvrofauditfirm ? req.body.indentificationnumbercvrofauditfirm : null,
          descriptionofauditor: req.body.descriptionofauditor ? req.body.descriptionofauditor : null,
          nameandsurnameofauditor: req.body.nameandsurnameofauditor ? req.body.nameandsurnameofauditor : null,
          audtiors_opinion: req.body.audtiors_opinion ? req.body.audtiors_opinion : null,
          audtiors_description: req.body.audtiors_description ? req.body.audtiors_description : null,
          auditors_statement_on_management_review: req.body.auditors_statement_on_management_review ? req.body.auditors_statement_on_management_review : null,
          responsibility_management: req.body.responsibility_management ? req.body.responsibility_management : null,
          responsibility_auditor: req.body.responsibility_auditor ? req.body.responsibility_auditor : null,
          auditor_comments: req.body.auditor_comments ? req.body.auditor_comments : null,
          management_review: req.body.management_review ? req.body.management_review : null,
          name_of_financial_institution: req.body.name_of_financial_institution ? req.body.name_of_financial_institution : null,
          name_of_law_firm: req.body.name_of_law_firm ? req.body.name_of_law_firm : null,
          averagenumberofemployees: req.body.averagenumberofemployees ? req.body.averagenumberofemployees : null,
          ifrs: req.body.ifrs,
          unit: req.body.unit,
          number_scale: req.body.number_scale,
          revenue: req.body.revenue ? req.body.revenue : null,
          other_income: req.body.other_income ? req.body.other_income : null,
          costs: req.body.costs ? req.body.costs : null,
          gross_result: req.body.gross_result ? req.body.gross_result : null,
          operating_costs: req.body.operating_costs ? req.body.operating_costs : null,
          other_operating_income: req.body.other_operating_income ? req.body.other_operating_income : null,
          staff_expenses: req.body.staff_expenses ? req.body.staff_expenses : null,
          ebitda: req.body.ebitda ? req.body.ebitda : null,
          depreciation: req.body.depreciation ? req.body.depreciation : null,
          ebit: req.body.ebit ? req.body.ebit : null,
          interest_income: req.body.interest_income ? req.body.interest_income : null,
          interest_expenses: req.body.interest_expenses ? req.body.interest_expenses : null,
          other_net_financial_income: req.body.other_net_financial_income ? req.body.other_net_financial_income : null,
          net_financial_income: req.body.net_financial_income ? req.body.net_financial_income : null,
          ordinary_profit: req.body.ordinary_profit ? req.body.ordinary_profit : null,
          extraordinary_item: req.body.extraordinary_item ? req.body.extraordinary_item : null,
          profit_loss_before_tax: req.body.profit_loss_before_tax ? req.body.profit_loss_before_tax : null,
          tax_expenses: req.body.tax_expenses ? req.body.tax_expenses : null,
          profit_loss: req.body.profit_loss,
          goodwill: req.body.goodwill ? req.body.goodwill : null,
          other_intangible_assets: req.body.other_intangible_assets ? req.body.other_intangible_assets : null,
          intangible_assets: req.body.intangible_assets ? req.body.intangible_assets : null,
          land_and_buildings: req.body.land_and_buildings ? req.body.land_and_buildings : null,
          plant_equipment_and_fixtures: req.body.plant_equipment_and_fixtures ? req.body.plant_equipment_and_fixtures : null,
          other_property_plant_and_equipment: req.body.other_property_plant_and_equipment ? req.body.other_property_plant_and_equipment : null,
          property_plant_and_equipment: req.body.property_plant_and_equipment ? req.body.property_plant_and_equipment : null,
          noncurrent_receivables: req.body.noncurrent_receivables ? req.body.noncurrent_receivables : null,
          noncurrent_investments: req.body.noncurrent_investments ? req.body.noncurrent_investments : null,
          other_noncurrent_financial_assets: req.body.other_noncurrent_financial_assets ? req.body.other_noncurrent_financial_assets : null,
          noncurrent_financial_assets: req.body.noncurrent_financial_assets ? req.body.noncurrent_financial_assets : null,
          noncurrent_assets: req.body.noncurrent_assets ? req.body.noncurrent_assets : null,
          inventories: req.body.inventories ? req.body.inventories : null,
          current_prepayments: req.body.current_prepayments ? req.body.current_prepayments : null,
          short_term_receivables_from_sales_and_services: req.body.short_term_receivables_from_sales_and_services ? req.body.short_term_receivables_from_sales_and_services : null,
          short_term_receivables_from_group_enterprises: req.body.short_term_receivables_from_group_enterprises ? req.body.short_term_receivables_from_group_enterprises : null,
          other_short_term_receivables: req.body.other_short_term_receivables ? req.body.other_short_term_receivables : null,
          short_term_receivables: req.body.short_term_receivables ? req.body.short_term_receivables : null,
          current_financial_assets: req.body.current_financial_assets ? req.body.current_financial_assets : null,
          cash: req.body.cash ? req.body.cash : null,
          current_assets: req.body.current_assets ? req.body.current_assets : null,
          assets: req.body.assets,
          contributed_capital: req.body.contributed_capital,
          reserves: req.body.reserves ? req.body.reserves : null,
          dividend: req.body.dividend ? req.body.dividend : null,
          retained_earnings: req.body.retained_earnings ? req.body.retained_earnings : null,
          equity_before_minority_interests: req.body.equity_before_minority_interests ? req.body.equity_before_minority_interests : null,
          minority_interests: req.body.minority_interests ? req.body.minority_interests : null,
          equity: req.body.equity,
          provisions: req.body.provisions ? req.body.provisions : null,
          long_term_debt_to_group_enterprises: req.body.long_term_debt_to_group_enterprises ? req.body.long_term_debt_to_group_enterprises : null,
          long_term_debt_to_banks: req.body.long_term_debt_to_banks ? req.body.long_term_debt_to_banks : null,
          long_term_mortgage_debt: req.body.long_term_mortgage_debt ? req.body.long_term_mortgage_debt : null,
          equity_loan: req.body.equity_loan ? req.body.equity_loan : null,
          deferred_tax: req.body.deferred_tax ? req.body.deferred_tax : null,
          other_long_term_debt: req.body.other_long_term_debt ? req.body.other_long_term_debt : null,
          long_term_debt: req.body.long_term_debt ? req.body.long_term_debt : null,
          short_term_debt_to_group_enterprises: req.body.short_term_debt_to_group_enterprises ? req.body.short_term_debt_to_group_enterprises : null,
          short_term_debt_to_banks: req.body.short_term_debt_to_banks ? req.body.short_term_debt_to_banks : null,
          short_term_mortgage_debt: req.body.short_term_mortgage_debt ? req.body.short_term_mortgage_debt : null,
          short_term_trade_payables: req.body.short_term_trade_payables ? req.body.short_term_trade_payables : null,
          short_term_tax_payables: req.body.short_term_tax_payables ? req.body.short_term_tax_payables : null,
          other_short_term_debt: req.body.other_short_term_debt ? req.body.other_short_term_debt : null,
          short_term_debt: req.body.short_term_debt ? req.body.short_term_debt : null,
          debt: req.body.debt ? req.body.debt : null,
          liabilities_and_equity: req.body.liabilities_and_equity
        })
        .then(() => res.sendStatus(200))
        .catch((error) => {
          console.log(error);
          res.status(400).send(error)});
    }
  };